### ISSUE TITLE
Touchpad jumpiness 

### ISSUE THREAD

**Issue by LiohMoeller** [advancingu/XPS13Linux#5]
Touchpad is somewhat jumpy on default install 14.04 with latest updates. XPS is DE model. BIOS is A03.

**Comment by dchambers** [comment]
Is this fixed in 15.04? If so, could there be a `Fixed in 15.04` label to indicate this?

**Comment by anaran** [comment]
I still see this jumpiness in 15.04. Isn't this a duplicate of (or what does it distinguish from) issue #3 ?
I guess these issues need clearer definitions, e.g. like bugzilla mozilla user stories:
- What did you do? (steps to reproduce)
- What happened? (actual results)
- What should have happened? (expected results)

**Comment by superm1** [comment]
For 14.04 jumpiness issue, here is the fix:
http://www.dell.com/support/article/us/en/19/SLN297219/en

**Comment by dchambers** [comment]
@MarcusMoeller, are you able to confirm whether this issues is distinct from #3 (and if so what makes it different), and whether it can be fixed using the link @superm1 provided?

**Comment by superm1** [comment]
Ubuntu 14.04 by default uses the PS2 driver.
Ubuntu 15.04 by default uses the I2C + HID driver.
By definition they will not have the same mouse behaviors.  Any of these discussions should distinguish which version is being used.

The link I provided enables/forces the I2C mode on Ubuntu 14.04 using a backported I2C driver and HID stack.  If there were issues (such as palm detection) missing in Ubuntu 15.04, I wouldn't expect them to work properly here either.

**Comment by dchambers** [comment]
@superm1, have you seen the [related trackpad issue](https://github.com/advancingu/XPS13Linux/issues/14) just now opened by @anaran? Not sure if you can replicate or are already aware of this?

**Comment by superm1** [comment]
I took a quick look and can't replicate it.  If it's causing errors for you, you can configure the region for TopEdge using synclient to be lower, and that should help.

**Comment by anaran** [comment]
@superm1 Tried setting TopEdge 200 (and verified value is taking effect via synclient) but can't see a change. Still detects events on frame above touchpad and very top of touchpad.

**Comment by tarballz** [comment]
Are you using the Dell OEM Ubuntu install?  Cause they run kernel 3.13, upgrading to 3.19 helped me a lot.
